# vendor name in small letters, for example: amd or nmvidia or qualcomm
vendor: test
# github repository for the operator code
codeRepo: github.com/yevgeny-shnaidman/test-gpu-operator
# apiversion for the DeviceConfig
apiVersion: v1alpha1
# group scheme for the DeviceConfig
group: test
# domain for the DeviceConfig
domain: io
# pci vendor id of the targeted devices. will be used to target the nodes for kernel module deployment
pciVendorID: 2040
# the name of the main kernel module to insert. it will be also used to delete in-tree kernel module
kernelModuleName: testgpu
# default device plugin image: will be used in case not defined in the DeviceConfig
defaultDevicePluginImage: rocm/k8s-device-plugin 
# the path to the firmware inside the container image
imageFirmwarePath: testFirmwareDir/updates
# default driver version, will be used as a tag the image
defaultDriverVersion: el9-6.1.1
# default node labeller image to be used in case it is not defined in the DeviceConfig
defaultNodeLabellerImage:  rocm/k8s-device-plugin:labeller-latest
# operator image repo
operatorImage: quay.io/yshnaidm/test-gpu-operator
